[package]
name = "rusty_compressor"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
flate2 = "1.0" 
env_logger = "0.9"
serde = { version = "1.0", features = ["derive"] } 
serde_json = "1.0" 
dotenv = "0.15" 
